---
- name: Install package conditionnel
  hosts: webservers
  remote_user: root

  tasks:
    - name: Install apache2 & mysql on node 1 et 2
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apache2
        - mysql-server
      when: ansible_hostname == "node01" or ansible_hostname == "node02"

    - name: Install git, nginx & cowsay on node 3
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - git
        - nginx
        - cowsay
      when: ansible_hostname == "node03"

    - name: Install ufw
      ansible.builtin.package:
        name: ufw
        state: present
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Allow firewall
      community.general.ufw:
        state: enabled
        policy: allow
      when: ansible_distribution == "Ubuntu"

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Change index.html content
      ansible.builtin.copy:
        content: "Bonjour depuis Ansible sur {{ ansible_hostname }}"
        dest: /var/www/html/index.html
        mode: '0644'
      when: "'apache2' in ansible_facts.packages or 'nginx' in ansible_facts.packages"

    - name: Start apache2
      ansible.builtin.service:
        name: apache2
        state: started
      when: "'apache2' in ansible_facts.packages"
      tags: apache

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
      when: "'nginx' in ansible_facts.packages"

    - name: Try call server
      ansible.builtin.uri:
        url: http://localhost
        return_content: true
      register: server_response

    - name: Show response
      ansible.builtin.debug:
        msg: "{{ server_response.content }}"

    - name: Déterminer le contenu à écrire dans /etc/jour
      ansible.builtin.set_fact:
        contenu_jour: >-
          {% if ansible_date_time.day | int % 2 == 0 and ansible_date_time.hour | int >= 12 %}
            Pair et plus tard que midi
          {% elif ansible_date_time.day | int % 2 == 0 and ansible_date_time.hour | int < 12 %}
            Pair et avant midi
          {% elif ansible_date_time.day | int % 2 == 1 and ansible_date_time.hour | int >= 12 %}
            Impair et plus tard que midi
          {% else %}
            Impair et avant midi
          {% endif %}

    - name: Write content in /etc/jour
      ansible.builtin.copy:
        content: "{{ contenu_jour }}"
        dest: /etc/jour
        mode: '0644'
