---
- name: Install ufw
  ansible.builtin.package:
    name: ufw
    state: present
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Allow firewall
  community.general.ufw:
    state: enabled
    policy: allow
  when: ansible_distribution == "Ubuntu"

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Change index.html content
  ansible.builtin.copy:
    content: "Bonjour depuis Ansible sur {{ ansible_hostname }}"
    dest: /var/www/html/index.html
    mode: '0644'
  when: "'apache2' in ansible_facts.packages or 'nginx' in ansible_facts.packages"

- name: Start apache2
  ansible.builtin.service:
    name: apache2
    state: started
  when: "'apache2' in ansible_facts.packages"

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
  when: "'nginx' in ansible_facts.packages"
